### ISSUE TITLE
Unicode 14.0 Beta

### ISSUE THREAD

**Issue by data-man** [christianparpart/libunicode#12]
The great library, thank you!

As I assume, first of all, you developed it for Contour.
According to https://github.com/ThomasDickey/uniset-snapshots `xterm` already uses Unicode 14.0.
In my [UCD_14](https://github.com/data-man/libunicode/tree/UCD_14) branch I tried to do this.
What do you think?

*NB: all tests updated to Catch v3.*

**Comment by christianparpart** [comment]
I love it!

But i would prefer to namespace by unicode version in order to give access to both/ more versions. What do you think?

So that if you request the script of a Codepoint in unicode 13, the API call would be `unicode::v13::script(...)` with the main namespace importing the latest version (i think libstdc++ is doing there exact same truck).

But i am absolutely fine in doing the fiddling myself. :)

Many thanks!

**Comment by christianparpart** [comment]
Because that fiddling might be more invasive.

**Comment by data-man** [comment]
> What do you think?

Won't that increase binaries' size?

Just for note, there're some good C++17 Unicode libraries (IMO):
https://github.com/yhirose/cpp-unicodelib
https://github.com/cor3ntin/ext-unicode-db

**Comment by christianparpart** [comment]
yes it will. it's also not a hard requirement to me personally. it was an idea that I thought might have made sense. My motivation here mainly (more presicly: exclusively) comes from some Terminal Emulator developers that think about improving Unicode support in terminals think they still need to support Unicode 8 behavior vs later behavior. Reason behind is that sometimes (at least once) the east asian width of a character has changed across the Unicode versions (specifically between version 8 and 9). I am not sure there is anything else really important that changed - also in later versions.

So if you ask me, i'm also fine in just having the latest version. :)

Thx also for the links of the other projects. I however doubt I'll drop this project here, but instead improve on it steadily (still much to add, such as BiDi support in order to support bidi languages in Contour some time in the future.)

**Comment by data-man** [comment]
> i'm also fine in just having the latest version

So could I do PR? ;)

**Comment by christianparpart** [comment]
> > i'm also fine in just having the latest version
> 
> So could I do PR? ;)

yes, please. :)

**Comment by data-man** [comment]
One last question, probably: with the updated 3rdparty libraries?

**Comment by christianparpart** [comment]
> One last question, probably: with the updated 3rdparty libraries?

:+1: :)

**Comment by data-man** [comment]
> improving Unicode support in terminals think they still need to support Unicode 8 behavior vs later behavior.

I think port https://github.com/jquast/ucs-detect to C++ can be useful in this library.
?

**Comment by christianparpart** [comment]
> > improving Unicode support in terminals think they still need to support Unicode 8 behavior vs later behavior.
> 
> I think port https://github.com/jquast/ucs-detect to C++ can be useful in this library.
> ?

I don't know yet (i am on smartphone right now) but i will have a look at it. :)
